### ISSUE TITLE
Lua error Actionbar

### ISSUE THREAD

**Issue by BipolarBasil** [shagu/pfUI#1033] opened 2021-03-14 11:38 UTC
Hey, first of all, awesome addon. really easy to get by with and wish there was a 3.3.5 vers of it too but well well :) 
I ve startet getting these lua errors from today. had the addons 2 days only so I should have the latest version.

![image](https://user-images.githubusercontent.com/80625706/111066971-1a052a00-84c2-11eb-8b5e-3f8f5b9b3812.png)

what can it be? playing turtle-wow 1.1.12.1

**Comment by shagu** [comment] 2021-03-15 14:50
Did you tried to disable other addons to check if it is some sort of addon conflict?
Also please scroll your chat up to make sure its the first error message appearing.

**Comment by Panlher** [comment] 2021-05-05 22:19
I have the same error but my lines are 710 and 720, I disable all my addons and the problem continue, all UI of pfui addon disapear and come back the blizzard UI, I use the pfUI spanish version, one thing more when I restart the options and all UI of pfUI, the error disapear but this is for a short time, because when I personalice the addon and relong the error come back, sorry for my english I speak spanish :)

**Comment by shagu** [comment] 2021-05-05 22:40
Please post a screenshot of the exact errors you get right after a relog

**Comment by Panlher** [comment] 2021-05-05 23:10
![WoWScrnShot_050521_180257](https://user-images.githubusercontent.com/83733291/117220446-3abc7280-add5-11eb-97fe-5a3a7c80a288.jpg)
![WoWScrnShot_050521_180313](https://user-images.githubusercontent.com/83733291/117220489-4d36ac00-add5-11eb-8042-c997b098442d.jpg)
In the UI is visible my character and the minimap only, but not the actionbars

**Comment by Panlher** [comment] 2021-05-06 01:46
More information for this error, the option that make it is the option of meta key I adjunt screenshots when I disable this option and when I able this option, the option is where stay my mouse.
![WoWScrnShot_050521_213113](https://user-images.githubusercontent.com/83733291/117230455-208d8f00-adeb-11eb-8700-c8aa2d0862ee.jpg)
![WoWScrnShot_050521_212440](https://user-images.githubusercontent.com/83733291/117230476-2c795100-adeb-11eb-91e8-cb2752266e7c.jpg)

**Comment by shagu** [comment] 2021-05-06 08:13
@Panlher Thanks for your detailed report. Sadly, I was not able to exactly reproduce it, it is probably some sort of combined addon-setting/client-setting/server related issue. However, I think I understood what is causing it. It's most likely now fixed with the latest commit: https://github.com/shagu/pfUI/commit/c840a70175cbdaced87def04e6b97f2f497ac096

Please try again with the latest version of pfUI :)

**Closed** 2021-05-08 13:46 UTC
