### ISSUE TITLE
Extra action bars not the same height

### ISSUE THREAD

**Issue by mrrosh** [shagu/pfUI#106] opened 2016-11-17 11:14 UTC
I've changed the border size to 1 (icon size 32 but doesn't make any difference) and the Bottom Right ActionBar is not the same height with the Right ActionBar, the first one is SLIGHTLY bigger, by 1px or something like that: http://i.imgur.com/QTtEux0.png

**Comment by shagu** [comment] 2016-11-17 20:13
For me, it looks like a Gameclient/Graphic bug. I found many similar bugs very often on other frames. 
As far as I found out, this is related to the scaling of frames, and how your graphic card is blurring/filtering scaled frames. If that's the case for you, I have no possibilities to intervene there.

Please try to set your UI-Scaling to 1.0 and scale both frames to 2.0 via the "unlock".
If the Problem still occurs, it's a bug in pfUI otherwise I'd just close this as "won't fix". 

I tried to reproduce, but I wasn't able to achieve your issue on my system: 
_UI-Scale 0.9 (1920x1080), Intel Graphics, OpenGL, Linux/Wine 1.9.23_

**Comment by Voidmenull** [comment] 2016-11-18 23:49
i can confirm this
it comes from scaling and the client renderer
pixelborders can be a problem there :/

**Closed** 2016-11-19 14:11 UTC
Labels: wontfix
