### ISSUE TITLE
ArchiTotem does not work under pfUI

### ISSUE THREAD

**Issue by Faymiony** [shagu/pfUI#786] opened 2017-12-13 09:30 UTC
Hi shagu, i play Shaman in LH, but i found that the ArchiTotem addons didnt work in pfUI, it was displayed in screen, but cant click the button to cast any totem, is it a bug?

**Comment by Road-block** [comment] 2017-12-15 16:15
What level is your shaman?

**Comment by Faymiony** [comment] 2017-12-18 02:10
50

**Comment by Road-block** [comment] 2017-12-18 11:23
The reason I asked about your level is that due to limitations of the API in classic ArchiTotem starts with all the totems a max level character would know but some of the buttons will simply not correspond to spells in lower levels.  
Is it all the totems that don't work? Or just some of them?  
Trying to understand if it's a general problem with the addon (I don't play a shaman and I only cleaned up that old addon for a friend)

**Comment by Faymiony** [comment] 2017-12-19 03:07
yea, all totems are not working, i can see ArchiTotem addons is displayed on screen, but cant click it, no action.

**Comment by Faymiony** [comment] 2017-12-19 03:09
yea, i get what you mean, shaman learn totem in different levels, but ArchiTotem display all totem even at level 1, at that moment some totem you cant click, only those you already learnt can be clicked/cast. but what i feedback is not this case, it is maybe a bug?

**Comment by Road-block** [comment] 2017-12-19 03:14
Looks that way, I'll have to run it along-side pfUI and see.

**Comment by Faymiony** [comment] 2017-12-19 03:16
that will be great appreciate.

**Comment by Road-block** [comment] 2017-12-19 18:53
I can't reproduce your problem. 
I fixed a couple unrelated things on ArchiTotem but didn't find anything that would break it with pfUI.  
Where you using my version of [ArchiTotem](https://github.com/Road-block/ArchiTotem/releases/latest)?   
[![IMAGE ALT TEXT](http://img.youtube.com/vi/SkqjwRq57U4/0.jpg)](https://youtu.be/SkqjwRq57U4 "pfUI & ArchiTotem")

**Comment by Faymiony** [comment] 2017-12-20 07:16
Ops, i am using pfUI chinese version, let me show you tonight, buti add some additional addons, so probably that addons crash with AT. (i am not sure)

**Comment by Road-block** [comment] 2017-12-20 07:48
> Ops, i am using pfUI chinese version

Wait, wait a minute. 😄   
You're playing on a Chinese client?  
Does ArchiTotem work on its own?  
ArchiTotem is using CastSpellByName() internally with the English names of the spells.  
Example: https://github.com/Road-block/ArchiTotem/blob/4dad9c4c96e42b92dff59233990d0b6fe9465872/ArchiTotem.lua#L74

I think @shagu can close this. It's not related to pfUI at all.  
Feel free to submit a ticket to ArchiTotem but make sure you test it alone first without other addons.

**Comment by Faymiony** [comment] 2017-12-20 09:09
yes, there is chinese version ArchiTotem available.

**Comment by Road-block** [comment] 2017-12-20 09:18
You need to provide more info mate.  
Where is that Chinese version of ArchiTotem?  
It's impossible to debug unknown addons, that we don't have the code for.

**Comment by Faymiony** [comment] 2017-12-21 01:34
under English client, everything is working fine. so i guess it is not capable in chinese client pfUI and chinese ArchiTotem. this topic can close.

**Comment by Road-block** [comment] 2017-12-21 04:50
Can you share Chinese ArchiTotem? At least then I have a chance to look at it.

**Comment by Faymiony** [comment] 2017-12-21 07:10
https://wetransfer.com/downloads/c01b85fead0a31f9f67db208274db1f020171221071025/873b68a2c27fa5b6207faa61a72ac57520171221071025/40928c

**Comment by g34651684** [comment] 2017-12-23 03:49
@Faymiony 你的图腾大师不能和pfui共用吗？应该是可以的，我30级的萨满小号共用无冲突。
http://i2.fuimg.com/609861/487297b3d8d56651.png

**Comment by Faymiony** [comment] 2017-12-26 09:55
这样啊？我用贴吧yong发布的中文端整合插件。不能和图腾大师一起用，但是英文端的可以用。

**Closed** 2018-04-10 22:37 UTC
Labels: invalid
