### ISSUE TITLE
bags: attempt to index field (nil value)

### ISSUE THREAD

**Issue by Lev6** [shagu/pfUI#1323] opened 2024-09-18 05:54 UTC
![image](https://github.com/user-attachments/assets/8b3eec77-a3ae-4d0b-8ac1-be657e01ab88)
Error
when moving the quiver of arrows it gives this error

**Comment by shagu** [comment] 2024-09-18 07:56
Hello, I was not able to reproduce your issue. I don't know why this entry was not initialized for you.
I have updated pfUI to check for existence of the field before using it, so the error should no longer happen.

Fixed via: https://github.com/shagu/pfUI/commit/fd4df67eb4b8192b40bd3a3a92c01bf37d33514b

**Closed by shagu** 2024-09-18 07:56 UTC
Labels: bug, cannot reproduce
