### ISSUE TITLE
loot: can't set banker and disenchanter if target not in group

### ISSUE THREAD

**Issue by Grookshank** [shagu/pfUI#791] opened 2017-12-17 20:41 UTC
See title: When I try to set a banker and disenchanter, the options only show when the player is in my group. They do not show, if they are not in my group, but in the same raid.

**Comment by Grookshank** [comment] 2017-12-17 20:51
See: https://www.twitch.tv/videos/210374470?t=10m03s

**Comment by Road-block** [comment] 2017-12-17 21:38
This is a limitation of the context menu in vanilla.  
The same happens with default client and masterlooter menu.  
If the raid member is not in your party you can only switch master looter through the slash command `/master Name`   
I'll take a look if a workaround for the default behavior is easy / possible but this is not a bug (not an unintended consequence)

**Comment by Grookshank** [comment] 2017-12-17 21:47
Ok, thanks for the explanation. Maybe something like /pf_loot_banker and /pf_loot_disenchanter would do the trick?

**Comment by Road-block** [comment] 2017-12-18 15:31
I have a fix for this, but while looking it over I found another problem with the code so it will take a little bit before I submit something for review.

**Comment by Road-block** [comment] 2017-12-19 17:30
Work is done on my fork, the commits are just rebase on subsequent mainline commits, no changes are needed.

**Comment by shagu** [comment] 2017-12-20 19:56
Thanks @Road-block :)

https://github.com/shagu/pfUI/commit/f13be1d68f5f790a6fc5c730d5204ff7278b4c8e

**Closed** 2017-12-20 19:55 UTC
