### ISSUE TITLE
Weird loot window behavior when opening containers

### ISSUE THREAD

**Issue by Cruzix** [shagu/pfUI#97] opened 2016-11-13 19:31 UTC
Heres a video of me opening a container with 8 items in it https://youtu.be/22EHuMm_wJ0 quite a few weird things happend;

First I tried to open the container and its icon turned gray and I got an error (http://imgur.com/a/XYXKF) which prevented me from opening it so I had to use an ability to interrupt my attempt at opening the container (used shadowmeld) since hitting escape/closing the bag didnt work. 
I then tried to open the container after interrupting my first attempt and it worked, however there was so much loot in the container that the loot window went off screen and there was no way of closing it other than using an ability again (shadowmeld)

Not sure if fixing the error provided will fix all these issues but if not then maybe make the loot window not be able to go off screen and also add a X in the corner to close the window or something similar

**Comment by shagu** [comment] 2016-11-14 23:11
The error should be fixed with this commit: https://github.com/shagu/pfUI/commit/b7abc07b4bdd87d6181afeddac0c0fb0ab8bdbc2

**Comment by Cruzix** [comment] 2016-11-15 11:27
Yep that fixed the error! :)

A little follow up though since some of the bugs are still happening:
- Loot window is able to go off screen
- No way of closing the loot window, and if you hit escape to close it you wont be able to access the container unless you use an ability such as shadowmeld or any other ability

I made a comparison video of how it works with pfUI and standard UI https://youtu.be/96U-O415YGA

Bonus bug (lol 😄): 
http://imgur.com/a/oIv0K
After the latest update it seems that the last bag slots are getting slightly clipped by the panel

**Comment by shagu** [comment] 2016-11-15 20:10
https://github.com/shagu/pfUI/commit/022b04a38df57e8ddc44e366d971e1a0fb29020f

Regarding your bonus bug, your whole bag window is weird. I cannot reproduce that. 
Maybe related to this? https://github.com/shagu/pfUI/issues/66

**Closed by shagu** 2016-11-15 20:10 UTC
Labels: bug

**Comment by Cruzix** [comment] 2016-11-15 20:32
Hmm I usually play on Borderless Fullscreen 1920x1080, also tried on Fullscreen 1920x1080 but it still clips a bit. Im not using the UI scale setting in video options. Weird

**Comment by shagu** [comment] 2016-11-15 20:34
Did you've tried to disable all other addons?

**Comment by Cruzix** [comment] 2016-11-15 21:03
Yes - however I just tried using the "Reset All" button in the settings and that fixed it, gonna try to set it up as before and have a look at what setting makes the slots clip

**Comment by Cruzix** [comment] 2016-11-15 21:06
Found it
ActionBar > Border, set that to anything other than 2 (standard) and it makes the bag look completely different

**Comment by shagu** [comment] 2016-11-15 21:42
https://github.com/shagu/pfUI/issues/102
