### ISSUE TITLE
a few ui bugs [bag,actionbar]

### ISSUE THREAD

**Issue by risuxd** [shagu/pfUI#73] opened 2016-11-08 19:55 UTC
hey!
found some new bugs and recorded a small video:
https://youtu.be/xlbFck6QIfs

- ~~actionbar double draw~~
- ~~no "darkened clockwise" counter on cooldowns/gcd in action bar~~
- bag sort button missing at startup (or after reload)

completely new WTF&Interface folders with pfUI & Clean_Up - Server: Kronos 2

hope its not my wow bugging or something.
thanks 👍

**Comment by shagu** [comment] 2016-11-08 20:11
actionbar double draw has been fixed here: https://github.com/shagu/pfUI/commit/e9eb3a0332bd0bad7462adab5f7f04fa317ae6e9

No clockwise cooldown works as designed, but there are plans to add some animations ;)

**Comment by risuxd** [comment] 2016-11-08 20:16
ah ok. 
sorry, I saw some grey flashing after using a skill and thought its already implemented! :)

**Comment by shagu** [comment] 2016-11-08 21:19
Weird, looks like kronos doesn't send BAG_UPDATE events on login, like my realm does.
It's fixed now: https://github.com/shagu/pfUI/commit/641ad14d69adba107d121453a81a0ee493e64f74

**Closed by shagu** 2016-11-08 21:19 UTC
Labels: bug

**Comment by risuxd** [comment] 2016-11-08 21:28
cheers! thanks mate!!
