### ISSUE TITLE
Mouseover on nameplate sometimes doesn't register

### ISSUE THREAD

**Issue by MagicNoodle** [shagu/pfUI#982] opened 2020-07-13 10:51 UTC
Sometimes when I mouseover a nameplate it doesn't seem to glow or show any tooltip, when I click to target it the hovering seems to work again. Mouseover macros don't work either when this happens. 

I have to note though that I have an issue with my mouse when I use a hardware cursor that it flickers when I move it around, though the nameplate problem seems to exist without it checked aswell.

**Comment by shagu** [comment] 2020-07-13 14:40
On which game version does this happen? Did you changed any nameplate settings?
So far I haven't been able to reproduce it.

Could you please cross check if the same does happen with the original nameplates?

**Comment by MagicNoodle** [comment] 2020-07-14 10:11
This is on 1.12.1. I've been able to reproduce the issue with deleted WDB/WTF no addons and fresh pfUI default settings. 

![WoWScrnShot_071420_120618](https://user-images.githubusercontent.com/23077028/87413514-b214e180-c5ca-11ea-9ea0-b34679c3d212.png)

As you can see there is no tooltip and the text is not yellow. The best place to see is at the edge of the bars, because in the middle you often mouseover the actual model.

**Comment by shagu** [comment] 2020-07-14 10:12
> This is on 1.12.1. I've been able to reproduce the issue with deleted WDB/WTF no addons and fresh pfUI default settings.

So you managed to reproduce it even without pfUI?

**Comment by MagicNoodle** [comment] 2020-07-14 10:14
No, sorry I meant no additional addons. This doesn't happen with default nameplates or even something like CustomNameplates.

**Comment by shagu** [comment] 2020-07-14 10:17
Are you sure to run the latest version? I'm standing here in durotar for a while now hovering nameplates and always see the hover effect. The pfUI nameplates don't remove the OnEnter and OnLeave of the original plates at all, so I don't see a reason why or how pfUI could change anything here in comparison to the original ones in terms of mouse-over (as long as default pfUI settings are in use).

**Comment by MagicNoodle** [comment] 2020-07-14 10:42
Actually I could reproduce the issue with default nameplates, but it never happens with CustomNameplates. I replaced all default fonts and had a patch from the Vanilla+ server but that didn't change anything. You should try it on the Strigid Owls the trick is to hover the model before running close enough for the nameplates to pop up and then it happens most often. It might just be a vanilla issue with certain models or some strange problem on my end.

**Comment by shagu** [comment] 2020-08-14 14:12
Closing this one, as I have not been able to reproduce it. I also don't see a reason why CustomNameplates is supposed to work, as it uses the same mechanism as pfUI and both are nothing else but a themed version of the regular nameplates. It also only seem to only happen with a few mobs and sounds like there's some sort of bad luck and (maybe) graphic drivers or other system components issue involved.

If there are any more insights that would help to fix the problem, feel free to reopen. However, since the original plates are also affected, i doubt that I could do anything on pfUI side to workaround the problem you have.

**Closed by shagu** 2020-08-14 14:12 UTC
Labels: cannot reproduce

**Comment by wexio** [comment] 2023-11-03 02:18
Hello shagu. I got an bugg with Pfui. I suddenly can't use mouseover with healing  /pfcast. i need to clickon him then i can mouseover players else if im not have anything on focus i heal myself. And i got self cast diactivated
